"""Make date nullable

Revision ID: 77404557ddcd
Revises: bb13fc0c0ee0
Create Date: 2024-10-19 20:18:18.060969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77404557ddcd'
down_revision = 'bb13fc0c0ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_slot', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_slot', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
