"""Add comment field to LeaveRequest model

Revision ID: 9f478f476e63
Revises: 6850365d88e7
Create Date: 2024-09-16 16:00:29.836089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f478f476e63'
down_revision = '6850365d88e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
